name: Build Android Package

on: 
   workflow_dispatch:

jobs:
  build-apk-for-android:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Cloning modlaucher repo and preparing for building
      run: |
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner imagemagick
    - name: Build APK
      run: |
        chmod +x scripts/build-apk.sh
        scripts/build-apk.sh
    - name: Rename APK
      run: |
         mv test-build-app/build/android/mod-signed.apk mod-release.apk
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mod-apk
        path: mod-release.apk
        retention-days: 7  # ลบใน 10 วัน