name: Build android package

#on:
#  workflow_dispatch:

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y make openjdk-8-jdk openjdk-8-jre ant-contrib python3-requests python3-pip
        pip3 install --user websocket-client  # ติดตั้งแบบ user แทน sudo

    - name: Download tools
      run: |
        git clone --depth 1 https://gitlab.com/LostGamer/ndk-binaries
        git clone --depth 1 https://gitlab.com/LostGamer/android-sdk
        wget https://github.com/hasandramali/tf2launcher-android/releases/download/v1.0/hl2libs.tar
        tar -xf hl2libs.tar
        sudo chmod 777 -R *

    - name: Build package
      env:
        DEPLOY_BRANCH: srceng-old-port
        COMMIT: ${{ github.sha }}
      run: |
        android/scripts/workflow.sh
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Build App
        path: bin/srceng-debug.apk
        if-no-files-found: error  # หากไม่มีไฟล์ให้แสดง error
        retention-days: 7  # ลบใน 7 วัน
